// Spiro Ganas
// 11/13/15
//
// Creates a variable that stores the DC data dictionary in the JSON format.
// This is used to feed data to the AngularJS website.

var DC_JSON = [
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC1",
    "DataElementName":"Submission Month",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"RIGHT([SUBMISSIONYEARMONTH],2) as \"SubmissionMonth\"",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC2",
    "DataElementName":"Submission Year",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"LEFT([SUBMISSIONYEARMONTH],4) as \"SubmissionYear\"",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC3",
    "DataElementName":"County of Member",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERCOUNTY",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"24",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC4",
    "DataElementName":"County of Service Provider",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERCOUNTY",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"24",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC5",
    "DataElementName":"Dental Claim ID",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"DENTALCLAIMID",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"7",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC6",
    "DataElementName":"Member ZIP code (first 3 digits)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LEFT([MEMBERZIPCODECLEANED],3) as \"Standardized_MemberZIPFirst3\"",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"3",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC7",
    "DataElementName":"Member ZIP code (5 digits)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LEFT([MEMBERZIPCODECLEANED],5) as \"Standardized_MemberZIP_5\"",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"5",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC8",
    "DataElementName":"Submission Control ID",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"SUBMISSIONCONTROLID",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"5",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC9",
    "DataElementName":"CHIA Incurred Date (Year and Month Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INCURREDDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"6",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC10",
    "DataElementName":"Medicaid/HSN Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICAIDHSNINDICATOR",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC11",
    "DataElementName":"Member Link EID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERLINKEID",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":null,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-DC13",
    "DataElementName":"Member Age At Service",
    "CHIA_Notes":"Age >89<=115 set to '999'",
    "NetezzaColumnName":"MEMBERAGEATSERVICECLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"3",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC001",
    "DataElementName":"Payer",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"ORGID",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"6",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"CHIA defined and maintained unique identifier",
    "ElementSubmissionGuideline":"Report the Unique Submitter ID as defined by CHIA here.  This must match the Submitter ID reported in HD002.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC003",
    "DataElementName":"Dental Insurance Type Code/Product",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DENTALINSURANCETYPECODEPRODUCT",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Type / Product Identification Code",
    "ElementSubmissionGuideline":"Report the code that defines the type of insurance under which this patient's claim line was processed.  EXAMPLE:  17 = Dental Maintenance Organization",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC004",
    "DataElementName":"Payer Claim Control Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAYERCLAIMCONTROLNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"35",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Payer Claim Control Identification",
    "ElementSubmissionGuideline":"Report the Unique identifier within the payer's system that applies to the entire claim.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC005",
    "DataElementName":"Line Counter",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LINECOUNTER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Incremental Line Counter",
    "ElementSubmissionGuideline":"Report the line number for this service within the claim.  Start with 1 and increment by 1 for each additional line.  Do not start with 0, include alphas or special characters.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC005A",
    "DataElementName":"Version Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"VERSIONNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Claim Service Line Version Number",
    "ElementSubmissionGuideline":"Report the version number of this claim service line. The version number begins with 0  and is incremented by 1 for each subsequent version of that service line.  No alpha or special characters.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC011",
    "DataElementName":"Individual Relationship Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INDIVIDUALRELATIONSHIPCODE",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Patient to Subscriber Relationship Code",
    "ElementSubmissionGuideline":"Report the value that defines the Patient's relationship to the Subscriber.  EXAMPLE:  20 = Self / Employee",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC012",
    "DataElementName":"Member Gender",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERGENDERCLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Patient's Gender",
    "ElementSubmissionGuideline":"Report patient gender as found on the claim in alpha format.  Used to validate clinical services when applicable and Unique Member ID.  EXAMPLE:  F = Female",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC013",
    "DataElementName":"Member Birth (Year Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERDATEOFBIRTHYEARCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's date of birth",
    "ElementSubmissionGuideline":"Report the date the member / patient was born in CCYYMMDD Format.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC013",
    "DataElementName":"Member Birth Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERDATEOFBIRTHMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's date of birth",
    "ElementSubmissionGuideline":"Report the date the member / patient was born in CCYYMMDD Format.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC014",
    "DataElementName":"Member City Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERCITYNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"City name of the Member/Patient",
    "ElementSubmissionGuideline":"Report the city name of the member / patient.  Used to validate Unique Member ID",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC015",
    "DataElementName":"Member State or Province",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSTATEORPROVINCE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"State / Province of the Patient",
    "ElementSubmissionGuideline":"Report the state of the patient as defined by the US Postal Service.  Report Province when Country Code does not = USA",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC017",
    "DataElementName":"Date Service Approved (AP Date)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATESERVICEAPPROVEDAPDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date Service Approved by Payer",
    "ElementSubmissionGuideline":"Report the date that the payer approved this claim line for payment in CCYYMMDD Format.  This element was designed to capture date other than the Paid date.  If Approved Date and Paid Date are the same, then the date here should match Paid Date.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC017",
    "DataElementName":"Date Service Approved (AP Date) - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATESERVICEAPPROVEDAPDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date Service Approved by Payer",
    "ElementSubmissionGuideline":"Report the date that the payer approved this claim line for payment in CCYYMMDD Format.  This element was designed to capture date other than the Paid date.  If Approved Date and Paid Date are the same, then the date here should match Paid Date.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC017",
    "DataElementName":"Date Service Approved (AP Date) - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATESERVICEAPPROVEDAPDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date Service Approved by Payer",
    "ElementSubmissionGuideline":"Report the date that the payer approved this claim line for payment in CCYYMMDD Format.  This element was designed to capture date other than the Paid date.  If Approved Date and Paid Date are the same, then the date here should match Paid Date.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC018",
    "DataElementName":"Service Provider Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERNUMBER_LINKAGE_ID",
    "Other_NOTE":"",
    "DataType":"Bigint",
    "DataLength":"",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Service Provider Identification Number",
    "ElementSubmissionGuideline":"Report the carrier / submitter assigned service provider number. This number should be the identifier used for internal identification purposes, and does not routinely change.  The value in this element must match a record in the provider file in PV002.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC020",
    "DataElementName":"National Service Provider ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"NATIONALSERVICEPROVIDERIDCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"National Provider Identification (NPI) of the Service Provider",
    "ElementSubmissionGuideline":"Report the Primary National Provider ID (NPI) here.  This ID should be found on the Provider File in the NPI element (PV039)",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC021",
    "DataElementName":"Service Provider Entity Type Qualifier",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERENTITYTYPEQUALIFIER",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Service Provider Entity Identifier Code",
    "ElementSubmissionGuideline":"Report the value that defines the provider entity type.  Only individuals should be identified with a 1.  Facilities, professional groups and clinic sites should all be identified with a 2.  EXAMPLE:  1 = Person",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC022",
    "DataElementName":"Service Provider First Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERFIRSTNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"25",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"First name of Service Provider",
    "ElementSubmissionGuideline":"Report the individual's first name here. If provider is a facility or organization , do not report any value here",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC023",
    "DataElementName":"Service Provider Middle Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERMIDDLENAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"25",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Middle initial of Service Provider",
    "ElementSubmissionGuideline":"Report the individual's middle name here. If provider is a facility or organization , do not report any value here",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC024",
    "DataElementName":"Service Provider Last Name or Organization Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERLASTNAMEORORGANIZATIONNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"60",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Last name or Organization Name of Service Provider",
    "ElementSubmissionGuideline":"Report the name of the organization or last name of the individual provider.  DC021 determines if this is an Organization or Individual Name reported here.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC025",
    "DataElementName":"Delegated Benefit Administrator Organization ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DELEGATEDBENEFITADMINISTRATORORGANIZATIONIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"6",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"CHIA defined and maintained Org ID for linking across submitters",
    "ElementSubmissionGuideline":"Riskholders report the OrgID of the DBA here. DBAs report the OrgID of the insurance carrier here. This element contains the CHIA assigned organization ID for the DBA or carrier.  Contact the MA APCD for the appropriate value. If no DBA is affiliated with this claim line do not report any value here: i.e., do not repeat the OrgID from DC001",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC026",
    "DataElementName":"Service Provider Specialty (Standard/Carrier-Specific Custom Values)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERSPECIALTYCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":1,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Taxonomy Code",
    "ElementSubmissionGuideline":"Report the standard code that defines this provider for this line of service.  Taxonomy values allow for the reporting of hygienists, assistants and laboratory technicians, where applicable, as well as Dentists, Orthodontists, etc.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC027",
    "DataElementName":"Service Provider City Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERCITYNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"City name of the Provider",
    "ElementSubmissionGuideline":"Report the Providers practice city location",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC028",
    "DataElementName":"Service Provider State",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERSTATE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"State of the Service Provider",
    "ElementSubmissionGuideline":"Report the state of the service providers as defined by the US Postal Service",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC029",
    "DataElementName":"Service Provider ZIP Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERZIPCODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Zip Code of the Service Provider",
    "ElementSubmissionGuideline":"Report the 5 or 9 digit Zip Code as defined by the US Postal Service.  When submitting the 9-digit Zip Code do not include hyphen.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC030",
    "DataElementName":"Facility Type - Professional",
    "CHIA_Notes":"",
    "NetezzaColumnName":"FACILITYTYPEPROFESSIONAL",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Place of Service Code",
    "ElementSubmissionGuideline":"Report the code the defines the location code where services were performed by the provider referenced on the claim",
    "Condition":"All",
    "ThresholdPercent":"0.8",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC031",
    "DataElementName":"Claim Status",
    "CHIA_Notes":"",
    "NetezzaColumnName":"CLAIMSTATUSCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Claim Line Status",
    "ElementSubmissionGuideline":"Report the  value that defines the payment status of this claim line",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC032",
    "DataElementName":"CDT Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"CDTCODE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"5",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"HCPCS / CDT Code",
    "ElementSubmissionGuideline":"Report the Common Dental Terminology code here",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC033",
    "DataElementName":"Procedure Modifier - 1",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROCEDUREMODIFIER1",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"HCPCS / CPT Code Modifier",
    "ElementSubmissionGuideline":"Report a valid Procedure modifier when a modifier clarifies / improves the reporting accuracy of the associated procedure code (DC032).",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC034",
    "DataElementName":"Procedure Modifier - 2",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROCEDUREMODIFIER2",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"HCPCS / CPT Code Modifier",
    "ElementSubmissionGuideline":"Report a valid Procedure modifier when a modifier clarifies / improves the reporting accuracy of the associated procedure code (DC032).",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC035",
    "DataElementName":"Date of Service - From",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEOFSERVICEFROM",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date of Service",
    "ElementSubmissionGuideline":"Report the date of service for this claim line in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC035",
    "DataElementName":"Date of Service - From Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEOFSERVICEFROMYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date of Service",
    "ElementSubmissionGuideline":"Report the date of service for this claim line in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC035",
    "DataElementName":"Date of Service - From Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEOFSERVICEFROMMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date of Service",
    "ElementSubmissionGuideline":"Report the date of service for this claim line in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC036",
    "DataElementName":"Date of Service - Thru",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEOFSERVICETHRU",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Last date of service for this service line.",
    "ElementSubmissionGuideline":"Report the end service date for the claim line in CCYYMMDD Format; it can equal DC035 when a single date of service is being reported.",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC036",
    "DataElementName":"Date of Service - Thru Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEOFSERVICETHRUYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Last date of service for this service line.",
    "ElementSubmissionGuideline":"Report the end service date for the claim line in CCYYMMDD Format; it can equal DC035 when a single date of service is being reported.",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC036",
    "DataElementName":"Date of Service - Thru Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEOFSERVICETHRUMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Last date of service for this service line.",
    "ElementSubmissionGuideline":"Report the end service date for the claim line in CCYYMMDD Format; it can equal DC035 when a single date of service is being reported.",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC037",
    "DataElementName":"Charge Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"CHARGEAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of provider charges for the claim line",
    "ElementSubmissionGuideline":"Report the amount the provider billed the insurance carrier for this claim line service.  Report 0 for services rendered in conjunction with other services on the claim.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC038",
    "DataElementName":"Paid Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAIDAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount paid by the carrier for the claim line",
    "ElementSubmissionGuideline":"Report the amount paid for the claim line.  Report 0 if line is paid as part of another procedure / claim line.  Do not report any value if the line is denied.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC039",
    "DataElementName":"Copay Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"COPAYAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of Copay member/patient is responsible to pay",
    "ElementSubmissionGuideline":"Report the amount that defines a preset, fixed amount for this claim line service that the patient is responsible to pay.  Report 0 if no Copay applies.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC040",
    "DataElementName":"Coinsurance Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"COINSURANCEAMOUNT",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of coinsurance member/patient is responsible to pay",
    "ElementSubmissionGuideline":"Report the amount that defines a calculated percentage amount for this claim line service that the patient is responsible to pay.  Report 0 if no Coinsurance applies. Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC041",
    "DataElementName":"Deductible Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DEDUCTIBLEAMOUNT",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of deductible member/patient is responsible to pay on the claim line",
    "ElementSubmissionGuideline":"Report the amount that defines a preset, fixed amount for this claim line service that the patient is responsible to pay.  Report 0 if no Deductible applies to service.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC042",
    "DataElementName":"Product ID Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTIDNUMBER_LINKAGE_ID",
    "Other_NOTE":"",
    "DataType":"Bigint",
    "DataLength":"",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Product Identification",
    "ElementSubmissionGuideline":"Report the submitter-assigned identifier as it appears in PR001 in the Product File.  This element is used to understand Product and Eligibility attributes of the member / subscriber as applied to this record",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC045",
    "DataElementName":"Paid Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAIDDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Paid date of the claim line",
    "ElementSubmissionGuideline":"Report the date that appears on the check and/or remit and/or explanation of benefits and corresponds to any and all types of payment in CCYYMMDD Format.  This can be the same date as Processed Date.  EXAMPLE: Claims paid in full, partial or zero paid.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC045",
    "DataElementName":"Paid Date Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAIDDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Paid date of the claim line",
    "ElementSubmissionGuideline":"Report the date that appears on the check and/or remit and/or explanation of benefits and corresponds to any and all types of payment in CCYYMMDD Format.  This can be the same date as Processed Date.  EXAMPLE: Claims paid in full, partial or zero paid.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC045",
    "DataElementName":"Paid Date Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAIDDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Paid date of the claim line",
    "ElementSubmissionGuideline":"Report the date that appears on the check and/or remit and/or explanation of benefits and corresponds to any and all types of payment in CCYYMMDD Format.  This can be the same date as Processed Date.  EXAMPLE: Claims paid in full, partial or zero paid.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC046",
    "DataElementName":"Allowed Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ALLOWEDAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Allowed Amount",
    "ElementSubmissionGuideline":"Report the maximum amount contractually allowed, and that a carrier will pay to a provider for a particular procedure or service.  This will vary by provider contract and most often it is less than or equal to the fee charged by the provider.  Report 0 when the claim line is denied. Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"Required when DC031 does not = 4, 22, or 23",
    "ThresholdPercent":"0.99",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC047",
    "DataElementName":"Tooth Number/Letter",
    "CHIA_Notes":"",
    "NetezzaColumnName":"TOOTHNUMBERLETTER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"20",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Tooth Number or Letter Identification",
    "ElementSubmissionGuideline":"Report the tooth identifier(s) when DC032 is within the given range",
    "Condition":"Required when DC032 = D2000 thru D2999",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC048",
    "DataElementName":"Dental Quadrant",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DENTALQUADRANT",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Dental Quadrant",
    "ElementSubmissionGuideline":"Report the standard quadrant identifier from the External Code Source here.  Provides further detail on procedure(s).",
    "Condition":"Required when DC032 reports quandrant-coded Dental Code",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC049",
    "DataElementName":"Tooth Surface",
    "CHIA_Notes":"",
    "NetezzaColumnName":"TOOTHSURFACECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Tooth Service Identification",
    "ElementSubmissionGuideline":"Report the tooth surface(s) that this service relates to.  Provides further detail on procedure. ",
    "Condition":"Required when DC032=D2000-D2709",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC056",
    "DataElementName":"Carrier Specific Unique Member ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"HASHCARRIERSPECIFICUNIQUEMEMBERIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Hash",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Member's Unique ID",
    "ElementSubmissionGuideline":"Report the identifier the carrier / submitter uses internally to uniquely identify the member. Used to validate Unique Member ID and link back to Member Eligibility (ME107)",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC057",
    "DataElementName":"Carrier Specific Unique Subscriber ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"HASHCARRIERSPECIFICUNIQUESUBSCRIBERIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Hash",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Subscriber's Unique ID",
    "ElementSubmissionGuideline":"Report the identifier the carrier / submitter uses internally to uniquely identify the subscriber. Used to validate Unique Member ID and link back to Member Eligibility (ME117)",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC059",
    "DataElementName":"Claim Line Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"CLAIMLINETYPECLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Claim Line Activity Type Code",
    "ElementSubmissionGuideline":"Report the code that defines the claim line status in terms of adjudication.   EXAMPLE:  O = Original",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC060",
    "DataElementName":"Former Claim Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"FORMERCLAIMNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"35",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Previous Claim Number",
    "ElementSubmissionGuideline":"Report the Claim Control Number (DC004) that was originally sent in a prior filing that this line corresponds to.  When reported, this data cannot equal its own DC004.  Use of �Former Claim Number� to version claims can only be used if approved by the MA APCD.  Contact the MA APCD for conditions of use. ",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC061",
    "DataElementName":"Diagnosis Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DIAGNOSISCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"7",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"ICD Diagnosis Code",
    "ElementSubmissionGuideline":"Report the ICD Diagnosis Code when applicable",
    "Condition":"Required when DC032 is within the ranges of D7000-D7999 or D9220 or D9221",
    "ThresholdPercent":"0.01",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC062",
    "DataElementName":"ICD Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ICDINDICATOR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"International Classification of Diseases version",
    "ElementSubmissionGuideline":"Report the value that defines whether the diagnoses on claim are ICD9 or ICD10.  EXAMPLE:  9 = ICD9",
    "Condition":"Required when DC061 is populated",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC063",
    "DataElementName":"Denied Flag",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DENIEDFLAG",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Denied Claim Line Indicator",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, Claim Line was denied.  ",
    "Condition":"Required when DC031 = 04",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC064",
    "DataElementName":"Denial Reason",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DENIEDREASONCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"20",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Denial Reason Code",
    "ElementSubmissionGuideline":"Report the code that defines the reason for denial of the claim line.  Carrier must submit denial reason codes in separate table to the APCD.",
    "Condition":"Required when DC063 = 1",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"DC065",
    "DataElementName":"Payment Arrangement Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAYMENTARRANGEMENTTYPE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Payment Arrangement Type Value",
    "ElementSubmissionGuideline":"Report the value that defines the contracted payment methodology for this claim line.  EXAMPLE:  02 = Fee for Service",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"Derived-DC12",
    "DataElementName":"Member Link MCL",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MCL",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":null,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"",
    "ThresholdPercent":"",
    "Category":""
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC006",
    "DataElementName":"Insured Group or Policy Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INSUREDGROUPORPOLICYNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Group / Policy Number",
    "ElementSubmissionGuideline":"Report the number that defines the insured group or policy.  Do not report the number that uniquely identifies the subscriber or member.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC007",
    "DataElementName":"Subscriber SSN",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUBSCRIBERSSN",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Subscriber's Social Security Number",
    "ElementSubmissionGuideline":"Report the Subscriber's SSN here; used to validate Unique Member ID; will not be passed into analytic file.  Do not use hyphen.  If not available do not report any value here.",
    "Condition":"All",
    "ThresholdPercent":"0.7",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC008",
    "DataElementName":"Plan Specific Contract Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PLANSPECIFICCONTRACTNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Contract Number",
    "ElementSubmissionGuideline":"Report the Plan assigned contract number.  Do not include values in this element that will distinguish one member of the family from another.  This should be the contract or certificate number for the subscriber and all of the dependents.",
    "Condition":"All",
    "ThresholdPercent":"0.7",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC009",
    "DataElementName":"Member Suffix or Sequence Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSUFFIXORSEQUENCENUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"20",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's Contract Sequence Number",
    "ElementSubmissionGuideline":"Report the unique number / identifier of the member / patient within the contract",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC010",
    "DataElementName":"Member Identification Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERIDENTIFICATIONCODE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's Social Security Number",
    "ElementSubmissionGuideline":"Report the patient's social security number here; used to validate Unique Member ID; will not be passed into analytic file.  Do not use hyphen.  If not available do not report any value here",
    "Condition":"All",
    "ThresholdPercent":"0.7",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC013",
    "DataElementName":"Member Date of Birth",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERDATEOFBIRTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's date of birth",
    "ElementSubmissionGuideline":"Report the date the member / patient was born in CCYYMMDD Format.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC016",
    "DataElementName":"Member ZIP Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERZIPCODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Zip Code of the Member / Patient",
    "ElementSubmissionGuideline":"Report the 5 or 9 digit Zip Code as defined by the United States Postal Service.  When submitting the 9-digit Zip Code do not include hyphen.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC019",
    "DataElementName":"Service Provider Tax ID Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SERVICEPROVIDERTAXIDNUMBER",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Service Provider's Tax ID number",
    "ElementSubmissionGuideline":"Report the Federal Tax ID of the Service Provider here. Do not use hyphen or alpha prefix.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC043",
    "DataElementName":"Member Street Address",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSTREETADDRESS",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Street address of the Member/Patient",
    "ElementSubmissionGuideline":"Report the patient / member's address.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.9",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC044",
    "DataElementName":"Billing Provider Tax ID Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"BILLINGPROVIDERTAXIDNUMBER",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"The Billing Provider's Federal Tax Identification Number (FTIN)",
    "ElementSubmissionGuideline":"Report the Federal Tax ID of the Billing Provider here. Do not use hyphen or alpha prefix.",
    "Condition":"All",
    "ThresholdPercent":"0.9",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC050",
    "DataElementName":"Subscriber Last Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUBSCRIBERLASTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"60",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Last name of Subscriber",
    "ElementSubmissionGuideline":"Report the last name of the subscriber.  Used to validate Unique Member ID.  Last name should exclude all punctuation, including hyphens and apostrophes.  Name should be contracted where punctuation is removed, do not report spaces.  EXAMPLE: O'Brien becomes OBRIEN; Carlton-Smythe becomes CARLTONSMYTHE",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC051",
    "DataElementName":"Subscriber First Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUBSCRIBERFIRSTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"25",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"First name of Subscriber",
    "ElementSubmissionGuideline":"Report the first name of the subscriber here. Used to validate Unique Member ID.  Exclude all punctuation, including hyphens and apostrophes.  Name should be contracted where punctuation is removed, do not report spaces.  EXAMPLE: Anne-Marie becomes ANNEMARIE",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC052",
    "DataElementName":"Subscriber Middle Initial",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUBSCRIBERMIDDLEINITIAL",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Middle initial of Subscriber",
    "ElementSubmissionGuideline":"Report the Subscriber's middle initial here. Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC053",
    "DataElementName":"Member Last Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERLASTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"60",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Last name of Member/Patient",
    "ElementSubmissionGuideline":"Report the last name of the patient / member here.  Used to validate Unique Member ID.  Last name should exclude all punctuation, including hyphens and apostrophes..  Name should be contracted where punctuation is removed, do not report spaces.  EXAMPLE: O'Brien becomes OBRIEN; Carlton-Smythe becomes CARLTONSMYTHE",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC054",
    "DataElementName":"Member First Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERFIRSTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"25",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"First name of Member/Patient",
    "ElementSubmissionGuideline":"Report the first name of the patient / member here. Used to validate Unique Member ID.  Exclude all punctuation, including hyphens and apostrophes.  Name should be contracted where punctuation is removed, do not report spaces.  EXAMPLE: Anne-Marie becomes ANNEMARIE",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC055",
    "DataElementName":"Member Middle Initial",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERMIDDLEINITIAL",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Middle initial of the Member/Patient",
    "ElementSubmissionGuideline":"Report the middle initial of the patient / member when available.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC058",
    "DataElementName":"Member Address 2",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERADDRESS2",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Secondary Street Address of the Member/Patient",
    "ElementSubmissionGuideline":"Report the address of member which may include apartment number or suite, or other secondary information besides the street.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC066",
    "DataElementName":"GIC ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"GICID",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"GIC Member ID",
    "ElementSubmissionGuideline":"Report the GIC Member Identification number as provided to GIC Plan Submitters.  If not applicable do not report any value here",
    "Condition":"Required when DC067 = 3",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"DC067",
    "DataElementName":"APCD ID Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"APCDIDCODE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member Enrollment Type",
    "ElementSubmissionGuideline":"Report the value that describes the member's / subscriber's enrollment into one of the predefined categories; aligns enrollment to appropriate editing and thresholds.  EXAMPLE:  1 = FIG - Fully Insured Commercial Group Enrollee.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  }
];