// Spiro Ganas
// 11/13/15
//
// Creates a variable that stores the PC data dictionary in the JSON format.
// This is used to feed data to the AngularJS website.

var PC_JSON = [
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC1",
    "DataElementName":"Submission Month",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"RIGHT([SUBMISSIONYEARMONTH],2) as \"SubmissionMonth\"",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC2",
    "DataElementName":"Submission Year",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"LEFT([SUBMISSIONYEARMONTH],4) as \"SubmissionYear\"",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC3",
    "DataElementName":"County of Member",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERCOUNTY",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"24",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC4",
    "DataElementName":"County of Pharmacy Location City",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PHARMACYLOCATIONCOUNTY",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"24",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC5",
    "DataElementName":"County of Prescribing Physician",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANCOUNTY",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"24",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC6",
    "DataElementName":"Member ZIP code (first 3 digits)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LEFT([MEMBERZIPCODECLEANED],3) as \"Standardized_MemberZIPFirst3\"",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"3",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC7",
    "DataElementName":"Member ZIP Code (5 digits)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LEFT([MEMBERZIPCODECLEANED],5) as \"Standardized_MemberZIP_5\"",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"5",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC8",
    "DataElementName":"Pharmacy Claim ID",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"PHARMACYCLAIMID",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC9",
    "DataElementName":"Submission Control ID",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"SUBMISSIONCONTROLID",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"5",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC10",
    "DataElementName":"CHIA Incurred Date (Year and Month Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INCURREDDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"6",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC11",
    "DataElementName":"Medicaid/HSN Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICAIDHSNINDICATOR",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC12",
    "DataElementName":"Member Link EID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERLINKEID",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":null,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC14",
    "DataElementName":"Member Age At Service",
    "CHIA_Notes":"Age >89<=115 set to '999'",
    "NetezzaColumnName":"MEMBERAGEATSERVICECLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"3",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PC15",
    "DataElementName":"Highest Version Paid Flag",
    "CHIA_Notes":"Recommended for identifying highest version claims - See documentation",
    "NetezzaColumnName":"VERSIONINDICATOR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":null,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC001",
    "DataElementName":"Payer",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"ORGID",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"6",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"CHIA defined and maintained unique identifier",
    "ElementSubmissionGuideline":"Report the Unique Submitter ID as defined by CHIA here.  This must match the Submitter ID reported in HD002",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC003",
    "DataElementName":"Insurance Type Code/Product",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INSURANCETYPECODEPRODUCT",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Type / Product Identification Code",
    "ElementSubmissionGuideline":"Report the code that defines the type of insurance under which this patient's claim line was processed.  EXAMPLE:  HM = HMO",
    "Condition":"All",
    "ThresholdPercent":"0.95",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC004",
    "DataElementName":"Payer Claim Control Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAYERCLAIMCONTROLNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"35",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Payer Claim Control Identification",
    "ElementSubmissionGuideline":"Report the Unique identifier within the payer's system that applies to the entire claim",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC005",
    "DataElementName":"Line Counter",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LINECOUNTER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Incremental Line Counter",
    "ElementSubmissionGuideline":"Report the line number for this service within the claim.  Start with 1 and increment by 1 for each additional line.  Do not start with 0, include alphas or special characters.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC005A",
    "DataElementName":"Version Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"VERSIONNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Claim Service Line Version Number",
    "ElementSubmissionGuideline":"Report the version number of this claim service line. The version number begins with 0  and is incremented by 1 for each subsequent version of that service line.  No alpha or special characters.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC011",
    "DataElementName":"Individual Relationship Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INDIVIDUALRELATIONSHIPCODE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Patient to Subscriber Relationship Code",
    "ElementSubmissionGuideline":"Report the value that defines the Patient's relationship to the Subscriber.  EXAMPLE:  20 = Self / Employee",
    "Condition":"All",
    "ThresholdPercent":"0.85",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC012",
    "DataElementName":"Member Gender",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERGENDERCLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Patient's Gender",
    "ElementSubmissionGuideline":"Report patient gender as found on the claim in alpha format.  Used to validate clinical services when applicable and Unique Member ID.  EXAMPLE:  F = Female",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC013",
    "DataElementName":"Member Birth (Year Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERDATEOFBIRTHYEARCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's date of birth",
    "ElementSubmissionGuideline":"Report the date the member / patient was born in CCYYMMDD Format.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC013",
    "DataElementName":"Member Birth (Month Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERDATEOFBIRTHMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's date of birth",
    "ElementSubmissionGuideline":"Report the date the member / patient was born in CCYYMMDD Format.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC014",
    "DataElementName":"Member City Name of Residence",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERCITYNAMEOFRESIDENCECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"City name of the Member/Patient",
    "ElementSubmissionGuideline":"Report the city name of the member / patient.  Used to validate Unique Member ID",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC015",
    "DataElementName":"Member State",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSTATE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"State / Province of the Patient",
    "ElementSubmissionGuideline":"Report the state of the patient as defined by the US Postal Service.  Report Province when Country Code does not = USA",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC017",
    "DataElementName":"Date Service Approved (AP Date)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATESERVICEAPPROVEDAPDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date Service Approved by Payer",
    "ElementSubmissionGuideline":"Report the date that the payer approved this claim line for payment in CCYYMMDD Format.  This element was designed to capture date other than the Paid date.  If Approved Date and Paid Date are the same, then the date here should match Paid Date.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC017",
    "DataElementName":"Date Service Approved (AP Date) - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATESERVICEAPPROVEDAPDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date Service Approved by Payer",
    "ElementSubmissionGuideline":"Report the date that the payer approved this claim line for payment in CCYYMMDD Format.  This element was designed to capture date other than the Paid date.  If Approved Date and Paid Date are the same, then the date here should match Paid Date.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC017",
    "DataElementName":"Date Service Approved (AP Date) - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATESERVICEAPPROVEDAPDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date Service Approved by Payer",
    "ElementSubmissionGuideline":"Report the date that the payer approved this claim line for payment in CCYYMMDD Format.  This element was designed to capture date other than the Paid date.  If Approved Date and Paid Date are the same, then the date here should match Paid Date.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC018",
    "DataElementName":"Pharmacy Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PHARMACYNUMBERCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Pharmacy Number",
    "ElementSubmissionGuideline":"Report either the NCPDP or NABP number of the dispensing pharmacy",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC020",
    "DataElementName":"Pharmacy Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PHARMACYNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"100",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Name of Pharmacy",
    "ElementSubmissionGuideline":"Report the name of the pharmacy here",
    "Condition":"All",
    "ThresholdPercent":"0.9",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC021",
    "DataElementName":"National Pharmacy ID Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"NATIONALPHARMACYIDNUMBERCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"National Provider Identification (NPI) of the Pharmacy",
    "ElementSubmissionGuideline":"Report the Primary National Provider ID (NPI) here.  This ID should be found on the Provider File in the NPI element (PV039)",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC022",
    "DataElementName":"Pharmacy Location City",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PHARMACYLOCATIONCITYCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"City name of the Pharmacy",
    "ElementSubmissionGuideline":"Report the city name of pharmacy - preferably pharmacy location",
    "Condition":"All",
    "ThresholdPercent":"0.85",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC023",
    "DataElementName":"Pharmacy Location State",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PHARMACYLOCATIONSTATE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"State of the Pharmacy",
    "ElementSubmissionGuideline":"Report the state where the dispensing pharmacy is located.",
    "Condition":"All",
    "ThresholdPercent":"0.9",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC024",
    "DataElementName":"Pharmacy ZIP Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PHARMACYLOCATIONZIPCODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Zip code of the Pharmacy",
    "ElementSubmissionGuideline":"Report the 5 or 9 digit Zip Code as defined by the United States Postal Service.  When submitting the 9-digit Zip Code do not include hyphen.",
    "Condition":"All",
    "ThresholdPercent":"0.9",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC025",
    "DataElementName":"Claim Status",
    "CHIA_Notes":"",
    "NetezzaColumnName":"CLAIMSTATUSCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Claim Line Status",
    "ElementSubmissionGuideline":"Report the  value that defines the payment status of this claim line",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC026",
    "DataElementName":"Drug Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DRUGCODECLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"11",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"National Drug Code (NDC)",
    "ElementSubmissionGuideline":"Report the NDC Code as defined by the FDA in 11 digit format (5-4-2) without hyphenation",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC027",
    "DataElementName":"Drug Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DRUGNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"80",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Name of the drug as supplied",
    "ElementSubmissionGuideline":"Report the name of the drug that aligns to the National Drug Code.  Do not report generic names with brand National Drug Codes",
    "Condition":"All",
    "ThresholdPercent":"0.95",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC028",
    "DataElementName":"New Prescription or Refill",
    "CHIA_Notes":"",
    "NetezzaColumnName":"NEWPRESCRIPTIONORREFILLCLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Prescription Status Indicator",
    "ElementSubmissionGuideline":"Report the status of prescription by numeric value.  EXAMPLE:  00 = new prescription; First Refill = 01, etc.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC029",
    "DataElementName":"Generic Drug Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"GENERICDRUGINDICATORCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Generic Drug Indicator",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, the drug reported is a generic. ",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC030",
    "DataElementName":"Dispense as Written Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DISPENSEASWRITTENCODE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Prescription Dispensing Activity Code",
    "ElementSubmissionGuideline":"Report the value that defines how the drug was dispensed.  EXAMPLE:  0 = Not dispensed as written",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC031",
    "DataElementName":"Compound Drug Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"COMPOUNDDRUGINDICATORCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Compound Drug Indicator",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, drug is a compound.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC032",
    "DataElementName":"Date Prescription Filled",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEPRESCRIPTIONFILLED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Prescription filled date",
    "ElementSubmissionGuideline":"Report the date the pharmacy filled AND dispensed prescription to the patient in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC032",
    "DataElementName":"Date Prescription Filled  (Year Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEPRESCRIPTIONFILLEDYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Prescription filled date",
    "ElementSubmissionGuideline":"Report the date the pharmacy filled AND dispensed prescription to the patient in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC032",
    "DataElementName":"Date Prescription Filled (Month Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEPRESCRIPTIONFILLEDMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Prescription filled date",
    "ElementSubmissionGuideline":"Report the date the pharmacy filled AND dispensed prescription to the patient in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC033",
    "DataElementName":"Quantity Dispensed",
    "CHIA_Notes":"",
    "NetezzaColumnName":"QUANTITYDISPENSED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Claim line units dispensed",
    "ElementSubmissionGuideline":"Report the number of metric units of medication dispensed",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC034",
    "DataElementName":"Days Supply",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DAYSSUPPLY",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Prescription Supply Days",
    "ElementSubmissionGuideline":"Report the number of days the prescription will last if taken as prescribed",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC035",
    "DataElementName":"Charge Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"CHARGEAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of provider charges for the claim line",
    "ElementSubmissionGuideline":"Report the amount the provider / dispensing facility billed the insurance carrier for this claim line service.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC036",
    "DataElementName":"Paid Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAIDAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount paid by the carrier for the claim line",
    "ElementSubmissionGuideline":"Report the amount paid for the claim line.  Report 0 if line is paid as part of another procedure / claim line.  Do not report any value if the line is denied.   Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC037",
    "DataElementName":"Ingredient Cost/List Price",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INGREDIENTCOSTLISTPRICE",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount defined as the List Price or Ingredient Cost",
    "ElementSubmissionGuideline":"Report the amount that defines this pharmaceutical cost / price.  Do not report any value if unknown. Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC038",
    "DataElementName":"Postage Amount Claimed",
    "CHIA_Notes":"",
    "NetezzaColumnName":"POSTAGEAMOUNTCLAIMED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of postage claimed on the claim line",
    "ElementSubmissionGuideline":"Report the amount of postage claimed for this claim line.  Report 0 if postage does not apply    Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC039",
    "DataElementName":"Dispensing Fee",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DISPENSINGFEECLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of dispensing fee for the claim line",
    "ElementSubmissionGuideline":"Report the amount that defines the dispensing fee.  Report 0 if fee does not apply. Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC040",
    "DataElementName":"Copay Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"COPAYAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of Copay member/patient is responsible to pay",
    "ElementSubmissionGuideline":"Report the amount that defines a preset, fixed amount for this claim line service that the patient is responsible to pay.  Report 0 if no Copay applies.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC041",
    "DataElementName":"Coinsurance Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"COINSURANCEAMOUNT",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of coinsurance member/patient is responsible to pay",
    "ElementSubmissionGuideline":"Report the amount that defines a calculated percentage amount for this claim line service that the patient is responsible to pay.  Report 0 if no Coinsurance applies. Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC042",
    "DataElementName":"Deductible Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DEDUCTIBLEAMOUNT",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of deductible member/patient is responsible to pay on the claim line",
    "ElementSubmissionGuideline":"Report the amount that defines a preset, fixed amount for this claim line service that the patient is responsible to pay.  Report 0 if no Deductible applies to service.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC043",
    "DataElementName":"Prescribing ProviderID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPROVIDERID_LINKAGE_ID",
    "Other_NOTE":"",
    "DataType":"BigInt",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Prescribing Provider Number",
    "ElementSubmissionGuideline":"Report the number of the prescribing provider here.  This value in this element must have corresponding Provider ID (PV002) in the Provider File.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC044",
    "DataElementName":"Prescribing Physician First Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANFIRSTNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"25",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"First name of Prescribing Physician",
    "ElementSubmissionGuideline":"Report the first name of the prescribing physician here.",
    "Condition":"All",
    "ThresholdPercent":"0.5",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC045",
    "DataElementName":"Prescribing Physician Middle Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANMIDDLENAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"25",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Middle initial of Prescribing Physician",
    "ElementSubmissionGuideline":"Report the middle name of the prescribing physician here.",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC046",
    "DataElementName":"Prescribing Physician Last Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANLASTNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"60",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Last name of Prescribing Physician",
    "ElementSubmissionGuideline":"Report the last name of the prescribing physician here.",
    "Condition":"All",
    "ThresholdPercent":"0.5",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC048",
    "DataElementName":"Prescribing Physician NPI - National Provider ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANNPICLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"National Provider Identification (NPI) of the Prescribing Provider",
    "ElementSubmissionGuideline":"Report the Primary National Provider ID (NPI) of the Prescribing Provider in PC043.  This ID should be found on the Provider File in the NPI element (PV039).  This element is looking to capture the NPI of an individual physician, not a group",
    "Condition":"All",
    "ThresholdPercent":"0.95",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC049",
    "DataElementName":"Prescribing Physician Plan Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANPLANNUMBERCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Carrier-assigned Provider Plan ID",
    "ElementSubmissionGuideline":"Report the prescriber's plan number here.  Do not report any value here if not contracted with the carrier.",
    "Condition":"All",
    "ThresholdPercent":"0.1",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC050",
    "DataElementName":"Prescribing Physician License Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANLICENSENUMBERCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Prescribing Physician License Number",
    "ElementSubmissionGuideline":"Report the state license number for the provider identified in PC043. For a doctor this is the medical license for a non-doctor this is the practice license.  Do not use zero-fill.  If not available, or not applicable, such as for a group or corporate entity, do not report any value here.  ",
    "Condition":"All",
    "ThresholdPercent":"0.1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC051",
    "DataElementName":"Prescribing Physician Street Address",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANSTREETADDRESSCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Street address of the Prescribing Physician",
    "ElementSubmissionGuideline":"Report the street address of the Prescribing Physician",
    "Condition":"All",
    "ThresholdPercent":"0.1",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC052",
    "DataElementName":"Prescribing Physician Street Address 2",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANSTREETADDRESS2CLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Secondary Street Address of the Prescribing Physician",
    "ElementSubmissionGuideline":"Report the street address of the Prescribing Physician that may contain office number, suite number of PO Box.",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC053",
    "DataElementName":"Prescribing Physician City",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANCITYCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"City name of the Prescribing Physician",
    "ElementSubmissionGuideline":"Report the Prescribing Physician City",
    "Condition":"All",
    "ThresholdPercent":"0.1",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC054",
    "DataElementName":"Prescribing Physician State",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANSTATE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"State of the Physician",
    "ElementSubmissionGuideline":"Report the state of the prescribing physician here.",
    "Condition":"All",
    "ThresholdPercent":"0.1",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC055",
    "DataElementName":"Prescribing Physician Zip",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANZIPCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Zip code of the Prescribing Physician",
    "ElementSubmissionGuideline":"Report the 5 or 9 digit Zip Code as defined by the United States Postal Service.  When submitting the 9-digit Zip Code do not include hyphen.",
    "Condition":"All",
    "ThresholdPercent":"0.1",
    "Category":"C "
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC056",
    "DataElementName":"Product ID Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTIDNUMBER_LINKAGE_ID",
    "Other_NOTE":"",
    "DataType":"BigInt",
    "DataLength":"",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Product Identification",
    "ElementSubmissionGuideline":"Report the submitter-assigned identifier as it appears in PR001 in the Product File.  This element is used to understand Product and Eligibility attributes of the member / subscriber as applied to this record",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC057",
    "DataElementName":"Mail Order pharmacy",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MAILORDERPHARMACY",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Mail Order Option",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, pharmacy is a mail order pharmacy",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC058",
    "DataElementName":"Script number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SCRIPTNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"20",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Prescription Number",
    "ElementSubmissionGuideline":"Report the unique identifier of the prescription",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC059",
    "DataElementName":"Recipient PCP ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"RECIPIENTPCPID_LINKAGE_ID",
    "Other_NOTE":"",
    "DataType":"BigInt",
    "DataLength":"",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Patient's PCP ID Number",
    "ElementSubmissionGuideline":"Report the member's PCP ID here.  The value in this element must have a corresponding Provider ID (PV002) in the Provider File.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC060",
    "DataElementName":"Single/Multiple Source Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SINGLEMULTIPLESOURCEINDICATOR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Drug Source Indicator",
    "ElementSubmissionGuideline":"Report the value that defines the availability of the pharmaceutical.  EXAMPLE:  1 = Multi-source brand",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC063",
    "DataElementName":"Paid Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAIDDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Paid date of the claim line",
    "ElementSubmissionGuideline":"Report the date that appears on the check and/or remit and/or explanation of benefits and corresponds to any and all types of payment in CCYYMMDD Format.  This can be the same date as Processed Date.  EXAMPLE: Claims paid in full, partial or zero paid",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC063",
    "DataElementName":"Paid Date - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAIDDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Paid date of the claim line",
    "ElementSubmissionGuideline":"Report the date that appears on the check and/or remit and/or explanation of benefits and corresponds to any and all types of payment in CCYYMMDD Format.  This can be the same date as Processed Date.  EXAMPLE: Claims paid in full, partial or zero paid",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC063",
    "DataElementName":"Paid Date - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAIDDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Paid date of the claim line",
    "ElementSubmissionGuideline":"Report the date that appears on the check and/or remit and/or explanation of benefits and corresponds to any and all types of payment in CCYYMMDD Format.  This can be the same date as Processed Date.  EXAMPLE: Claims paid in full, partial or zero paid",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC064",
    "DataElementName":"Date Prescription Written",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEPRESCRIPTIONWRITTEN",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date prescription was prescribed",
    "ElementSubmissionGuideline":"Report the date that was written on the prescription or called-in by the physician's office in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC064",
    "DataElementName":"Date Prescription Written  (Year Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEPRESCRIPTIONWRITTENYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"4",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date prescription was prescribed",
    "ElementSubmissionGuideline":"Report the date that was written on the prescription or called-in by the physician's office in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC064",
    "DataElementName":"Date Prescription Written (Month Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DATEPRESCRIPTIONWRITTENMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Date prescription was prescribed",
    "ElementSubmissionGuideline":"Report the date that was written on the prescription or called-in by the physician's office in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC066",
    "DataElementName":"Other Insurance Paid Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"OTHERINSURANCEPAIDAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount paid by a Primary / Prior Carrier",
    "ElementSubmissionGuideline":"Report the amount that a prior payer has paid for this claim line.  Indicates the submitting Payer is 'secondary' to the prior payer.  Only report 0 if the Prior Payer paid 0 towards this claim line, else do not report any value here.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"Required when PC025 = 02, 03, 20, or 21",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC068",
    "DataElementName":"Allowed amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ALLOWEDAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Allowed Amount",
    "ElementSubmissionGuideline":"Report the maximum amount contractually allowed, and that a carrier will pay to a provider for a particular procedure or service.  This will vary by provider contract and most often it is less than or equal to the fee charged by the pharmacy  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"Required when PC025 does not = 4, 22, or 23",
    "ThresholdPercent":"0.99",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC069",
    "DataElementName":"Member Self Pay Amount",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSELFPAYAMOUNT",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount member/patient paid out of pocket on the claim line",
    "ElementSubmissionGuideline":"Report the amount that the patient has paid beyond the copay structure.  Report 0 if patient has not paid towards this claim line. Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"All",
    "ThresholdPercent":"0.2",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC070",
    "DataElementName":"Rebate Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"REBATEINDICATOR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Drug Rebate Eligibility Indicator",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, drug is eligible for a rebate to any entity.  ",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC071",
    "DataElementName":"State Sales Tax",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STATESALESTAX",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount of applicable sales tax on the claim line",
    "ElementSubmissionGuideline":"Report the amount of state sales tax applied to this claim line.  Report 0 if state sales tax does not apply. Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"Required when PC023 does not = MA",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC072",
    "DataElementName":"Delegated Benefit Administrator Organization ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DELEGATEDBENEFITADMINISTRATORORGANIZATIONIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"6",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"CHIA defined and maintained Org ID for linking across submitters",
    "ElementSubmissionGuideline":"Riskholders report the OrgID of the DBA here. DBAs report the OrgID of the insurance carrier here. This element contains the CHIA assigned organization ID for the DBA.  Contact the APCD for the appropriate value. If no DBA is affiliated with this claim line do not report any value here: i.e., do not repeat the OrgID from PC001",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC073",
    "DataElementName":"Formulary Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"FORMULARYCODE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Formulary inclusion identifier",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, drug is on the formulary.  ",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC074",
    "DataElementName":"Route of Administration",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ROUTEOFADMINISTRATIONCLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Route of Administration",
    "ElementSubmissionGuideline":"Report Pharmaceutical Route of Administration Indicator that defines method of drug administration.  EXAMPLE:  11 = Oral",
    "Condition":"All",
    "ThresholdPercent":"0.8",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC075",
    "DataElementName":"Drug Unit of Measure",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DRUGUNITOFMEASURE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Units of Measure",
    "ElementSubmissionGuideline":"Report the code that defines the unit of measure for drug dispensed.  EXAMPLE:  EA = Each",
    "Condition":"All",
    "ThresholdPercent":"0.8",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC107",
    "DataElementName":"Carrier Specific Unique Member ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"HASHCARRIERSPECIFICUNIQUEMEMBERIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Hash",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Member's Unique ID",
    "ElementSubmissionGuideline":"Report the identifier the carrier / submitter uses internally to uniquely identify the member. Used to validate Unique Member ID and link back to Member Eligibility (ME107)",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC108",
    "DataElementName":"Carrier Specific Unique Subscriber ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"HASHCARRIERSPECIFICUNIQUESUBSCRIBERIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Hash",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Subscriber's Unique ID",
    "ElementSubmissionGuideline":"Report the identifier the carrier / submitter uses internally to uniquely identify the subscriber. Used to validate Unique Member ID and link back to Member Eligibility (ME117)",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC110",
    "DataElementName":"Claim Line Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"CLAIMLINETYPECLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Claim Line Activity Type Code",
    "ElementSubmissionGuideline":"Report the code that defines the claim line status in terms of adjudication.   EXAMPLE:  O = Original",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC111",
    "DataElementName":"Former Claim Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"FORMERCLAIMNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"35",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Previous Claim Number",
    "ElementSubmissionGuideline":"Report the Claim Control Number (PC004) that was originally sent in a prior filing that this line corresponds to.  When reported, this data cannot equal its own PC004.  Use of �Former Claim Number� to version claims can only be used if approved by the APCD.  Contact the APCD for conditions of use. ",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC112",
    "DataElementName":"Medicare Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICAREINDICATOR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Medicare Payment Applied",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, Medicare paid for part or all of services",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC114",
    "DataElementName":"Diagnosis Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DIAGNOSISCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"7",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"ICD Diagnosis Code",
    "ElementSubmissionGuideline":"Report the ICD Diagnosis Code when applicable",
    "Condition":"All",
    "ThresholdPercent":"0.01",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC115",
    "DataElementName":"ICD Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ICDINDICATOR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"International Classification of Diseases version",
    "ElementSubmissionGuideline":"Report the value that defines whether the diagnoses on claim are ICD9 or ICD10.  EXAMPLE:  9 = ICD9",
    "Condition":"Required when PC114 is populated",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC116",
    "DataElementName":"Denied Flag",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DENIEDFLAG",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Denied Claim Line Indicator",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, Claim Line was denied.  ",
    "Condition":"Required when PC025 = 04",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC117",
    "DataElementName":"Denial Reason",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DENIALREASONCLEANED",
    "Other_NOTE":"",
    "DataType":"Varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Denial Reason Code",
    "ElementSubmissionGuideline":"Report the code that defines the reason for denial of the claim line.  Carrier must submit denial reason codes in separate table to the APCD.",
    "Condition":"Required when PC116 = 1",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PC118",
    "DataElementName":"Payment Arrangement Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PAYMENTARRANGEMENTTYPE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"2",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Payment Arrangement Type Value",
    "ElementSubmissionGuideline":"Report the value that defines the contracted payment methodology for this claim line.  EXAMPLE:  02 = Fee for Service",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"Derived-PC13",
    "DataElementName":"Member Link MCL",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MCL",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":null,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC006",
    "DataElementName":"Insured Group or Policy Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INSUREDGROUPORPOLICYNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC007",
    "DataElementName":"Subscriber SSN",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUBSCRIBERSSN",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Subscriber's Social Security Number",
    "ElementSubmissionGuideline":"Report the Subscriber's SSN here; used to validate Unique Member ID; will not be passed into analytic file.  Do not use hyphen.  If not available do not report any value here",
    "Condition":"All",
    "ThresholdPercent":"0.85",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC008",
    "DataElementName":"Plan Specific Contract Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PLANSPECIFICCONTRACTNUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"30",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Contract Number",
    "ElementSubmissionGuideline":"Report the Plan assigned contract number.  Do not include values in this element that will distinguish one member of the family from another.  This should be the contract or certificate number for the subscriber and all of the dependents.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C "
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC009",
    "DataElementName":"Member Suffix or Sequence Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSUFFIXORSEQUENCENUMBER",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"20",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's Contract Sequence Number",
    "ElementSubmissionGuideline":"Report the unique number / identifier of the member within the contract",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC010",
    "DataElementName":"Member SSN",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSSN",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's Social Security Number",
    "ElementSubmissionGuideline":"Report the patient's social security number here; used to validate Unique Member ID; will not be passed into analytic file.  Do not use hyphen.  If not available do not report any value here",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC013",
    "DataElementName":"Member Date of Birth",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERDATEOFBIRTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"8",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member/Patient's date of birth",
    "ElementSubmissionGuideline":"Report the date the member / patient was born in CCYYMMDD Format.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC016",
    "DataElementName":"Member ZIP Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERZIPCODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Zip code of the Member / Patient",
    "ElementSubmissionGuideline":"Report the 5 or 9 digit Zip Code as defined by the United States Postal Service.  When submitting the 9-digit Zip Code do not include hyphen.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC019",
    "DataElementName":"Pharmacy Tax ID Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PHARMACYTAXIDNUMBER",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Pharmacy Tax Identification Number",
    "ElementSubmissionGuideline":"Report the Federal Tax ID of the Pharmacy here. Do not use hyphen or alpha prefix.",
    "Condition":"All",
    "ThresholdPercent":"0.2",
    "Category":"C "
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC047",
    "DataElementName":"Prescribing Physician DEA Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPHYSICIANDEANUMBER",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Prescribing DEA",
    "ElementSubmissionGuideline":"Report the Primary DEA number for the prescribing physician",
    "Condition":"All",
    "ThresholdPercent":"0.8",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC061",
    "DataElementName":"Member Street Address",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSTREETADDRESS",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Street address of the Member/Patient",
    "ElementSubmissionGuideline":"Report the patient / member's address.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.9",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC062",
    "DataElementName":"Billing Provider Tax ID Number",
    "CHIA_Notes":"",
    "NetezzaColumnName":"BILLINGPROVIDERTAXIDNUMBER",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"The Billing Provider's Federal Tax Identification Number (FTIN)",
    "ElementSubmissionGuideline":"Report the Federal Tax ID of the Billing Provider here. Do not use hyphen or alpha prefix.",
    "Condition":"All",
    "ThresholdPercent":"0.9",
    "Category":"C "
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC065",
    "DataElementName":"Coordination of Benefits/TPL Liability Amount - GIC Only",
    "CHIA_Notes":"",
    "NetezzaColumnName":"COORDINATIONOFBENEFITSTPLLIABILITYAMOUNT",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount due from a Secondary Carrier when known",
    "ElementSubmissionGuideline":"Report the amount that another carrier / insurer is liable for after submitting payer has processed this claim line.  Report 0 if there is no COB / TPL amount.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"Required when PC025 = 19, 20 or 21",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC067",
    "DataElementName":"Medicare Paid Amount - GIC Only",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICAREPAIDAMOUNTCLEANED",
    "Other_NOTE":"",
    "DataType":"�varchar",
    "DataLength":"10",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Amount Medicare paid on claim",
    "ElementSubmissionGuideline":"Report the amount Medicare paid towards this claim line.  Only report 0 here if Medicare paid 0.  If Medicare did not pay towards this claim line do not report any value here.  Do not code decimal or round up / down to whole dollars, code zero cents (00) when applicable.  EXAMPLE:  150.00 is reported as 15000; 150.70 is reported as 15070",
    "Condition":"Required when PC112 = 1",
    "ThresholdPercent":"0.98",
    "Category":"A1"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC101",
    "DataElementName":"Subscriber Last Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUBSCRIBERLASTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"60",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Last name of Subscriber",
    "ElementSubmissionGuideline":"Report the last name of the subscriber.  Used to validate Unique Member ID.  Last name should exclude all punctuation, including hyphens and apostrophes, and be reported in upper case.  Name should be contracted where punctuation is removed, do not report spaces.  EXAMPLE: O'Brien becomes OBRIEN; Carlton-Smythe becomes CARLTONSMYTHE",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC102",
    "DataElementName":"Subscriber First Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUBSCRIBERFIRSTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"25",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"First name of Subscriber",
    "ElementSubmissionGuideline":"Report the first name of the subscriber here. Used to validate Unique Member ID.  Exclude all punctuation, including hyphens and apostrophes.  Name should be contracted where punctuation is removed, do not report spaces.  EXAMPLE: Anne-Marie becomes ANNEMARIE",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC103",
    "DataElementName":"Subscriber Middle Initial",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUBSCRIBERMIDDLEINITIAL",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Middle initial of Subscriber",
    "ElementSubmissionGuideline":"Report the Subscriber's middle initial here. Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC104",
    "DataElementName":"Member Last Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERLASTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"60",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Last name of Member/Patient",
    "ElementSubmissionGuideline":"Report the last name of the patient / member here.  Used to validate Unique Member ID.  Last name should exclude all punctuation, including hyphens and apostrophes, and be reported in upper case.  Name should be contracted where punctuation is removed, do not report spaces.  EXAMPLE: O'Brien becomes OBRIEN; Carlton-Smythe becomes CARLTONSMYTHE",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC105",
    "DataElementName":"Member First Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERFIRSTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"25",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"First name of Member/Patient",
    "ElementSubmissionGuideline":"Report the first name of the patient / member here. Used to validate Unique Member ID.  Exclude all punctuation, including hyphens and apostrophes.  Name should be contracted where punctuation is removed, do not report spaces.  EXAMPLE: Anne-Marie becomes ANNEMARIE",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC106",
    "DataElementName":"Member Middle Initial",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERMIDDLEINITIAL",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Middle initial of the Member/Patient",
    "ElementSubmissionGuideline":"Report the middle initial of the patient / member when available.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC109",
    "DataElementName":"Member Street Address 2",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEMBERSTREETADDRESS2",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"50",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Secondary Street Address of the Member/Patient",
    "ElementSubmissionGuideline":"Report the address of member which may include apartment number or suite, or other secondary information besides the street.  Used to validate Unique Member ID.",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC113",
    "DataElementName":"Pregnancy Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PREGNANCYINDICATOR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Pregnancy",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, the patient is pregnant",
    "Condition":" Required when PC012=F",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC119",
    "DataElementName":"GIC ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"GICID",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":"9",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"GIC Member ID",
    "ElementSubmissionGuideline":"Report the GIC Member Identification number as provided to GIC Plan Submitters.  If not applicable do not report any value here",
    "Condition":"Required when PC120 = 3",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PC120",
    "DataElementName":"APCD ID Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"APCDIDCODE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":"1",
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Member Enrollment Type",
    "ElementSubmissionGuideline":"Report the value that describes the member's / subscriber's enrollment into one of the predefined categories; aligns enrollment to appropriate editing and thresholds.  EXAMPLE:  1 = FIG - Fully Insured Commercial Group Enrollee.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  }
];