// Spiro Ganas
// 11/13/15
//
// Creates a variable that stores the PR data dictionary in the JSON format.
// This is used to feed data to the AngularJS website.

var PR_JSON = [
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PR1",
    "DataElementName":"Release ID",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"RELEASEID",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":7,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PR2",
    "DataElementName":"Medicaid/HSN Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICAIDHSNINDICATOR",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":5,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PR3",
    "DataElementName":"Product Delegate",
    "CHIA_Notes":"New release 4.0 derived element",
    "NetezzaColumnName":"LINKINGPRODUCTDELEGATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"HD002",
    "DataElementName":"Payer",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"ORGID",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":6,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Header Submitter / Carrier ID defined by CHIA",
    "ElementSubmissionGuideline":"Report CHIA defined, unique Submitter ID here.  TR002 must match the Submitter ID reported here.  This ID is linked to other elements in the file for quality control",
    "Condition":"Mandatory",
    "ThresholdPercent":"1",
    "Category":"HM"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR001",
    "DataElementName":"Product ID number ",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LINKINGPRODUCTID",
    "Other_NOTE":"",
    "DataType":"BigInt",
    "DataLength":null,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Product Identification",
    "ElementSubmissionGuideline":"Report the submitter-assigned identifier that uniquely defines this product.  This identifier is used to link this Product line with its attributes to eligibility and claim lines.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR003",
    "DataElementName":"Carrier License Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"CARRIERLICENSETYPE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":3,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Carrier License Type",
    "ElementSubmissionGuideline":"Report the code that defines the License Type of this Product.  EXAMPLE:  COM = Commercial",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR004",
    "DataElementName":"Product Line of Business Model",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTLINEOFBUSINESSMODEL",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Line of Business / Insurance Model the Product relates to.",
    "ElementSubmissionGuideline":"Report the code that defines the Line of Business model that this product follows.  EXAMPLE:  12 = PPO",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR005",
    "DataElementName":"Insurance Plan Market",
    "CHIA_Notes":"",
    "NetezzaColumnName":"INSURANCEPLANMARKETCLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Insurance Plan Market Code",
    "ElementSubmissionGuideline":"Report the code that defines the market this product is sold into.  EXAMPLE:  GEMP = Group - Employer  ",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR006",
    "DataElementName":"Product Benefit Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTBENEFITTYPE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Benefit Options",
    "ElementSubmissionGuideline":"Report the value that defines the types of benefits covered under this product.  EXAMPLE:  1 = Medical Only",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR008",
    "DataElementName":"Risk Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"RISKTYPE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Risk Options",
    "ElementSubmissionGuideline":"Report the value that best describes the risk model that defines how eligibilities are  insured under this product line.   EXAMPLE:  1 = Fully Insured",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR009",
    "DataElementName":"Product Start Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTSTARTDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":8,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Product Start Date",
    "ElementSubmissionGuideline":"Report the first date that this product is active in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR009",
    "DataElementName":"Product Start Date - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTSTARTDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Product Start Date",
    "ElementSubmissionGuideline":"Report the first date that this product is active in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR009",
    "DataElementName":"Product Start Date - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTSTARTDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Product Start Date",
    "ElementSubmissionGuideline":"Report the first date that this product is active in CCYYMMDD Format.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR010",
    "DataElementName":"Product End Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTENDDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":8,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Product End Date",
    "ElementSubmissionGuideline":"Report the last date that this product is active in CCYYMMDD Format. If product is still active do not report any value here.",
    "Condition":"Required when PR011=2",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR010",
    "DataElementName":"Product End Date - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTENDDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Product End Date",
    "ElementSubmissionGuideline":"Report the last date that this product is active in CCYYMMDD Format. If product is still active do not report any value here.",
    "Condition":"Required when PR011=2",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR010",
    "DataElementName":"Product End Date - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTENDDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Product End Date",
    "ElementSubmissionGuideline":"Report the last date that this product is active in CCYYMMDD Format. If product is still active do not report any value here.",
    "Condition":"Required when PR011=2",
    "ThresholdPercent":"1",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR011",
    "DataElementName":"Product Active Flag",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTACTIVEFLAGCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Active Product",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, the Product is active",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR012",
    "DataElementName":"Annual Per Person Deductible Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ANNUALPERPERSONDEDUCTIBLECODECLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":3,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Per Person Deductible bandwidth reporting",
    "ElementSubmissionGuideline":"Report the value that defines the Total Per Person Deductible for all benefits under this product.  EXAMPLE:  000 = Plans with no Per Person Deductible",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR013",
    "DataElementName":"Annual Per Family Deductible Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ANNUALPERFAMILYDEDUCTIBLECODECLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":3,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Per Family Deductible bandwidth reporting",
    "ElementSubmissionGuideline":"Report the value that defines the Total Per Family Deductible for all benefits under this product.  EXAMPLE:  000 = Plans with no Per Family Deductible",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR014",
    "DataElementName":"Coordinated Care model",
    "CHIA_Notes":"",
    "NetezzaColumnName":"COORDINATEDCAREMODEL",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Clinical Coordination",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, Member's care is clinically coordinated/managed. ",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PR017",
    "DataElementName":"NAIC Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"NAICCODE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":5,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"National Association of Insurance Commissioners' Code",
    "ElementSubmissionGuideline":"Report the NAIC Code associated with the entity that maintains this product.  Entities that are not assigned a NAIC must not report any value here.",
    "Condition":"Required when Submitter is identified as a NAIC Coded entity",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PR002",
    "DataElementName":"Product Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRODUCTNAME",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":70,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Submitter defined Product name",
    "ElementSubmissionGuideline":"Report a unique name for every Product in a Carrier's system.  For Products with identical names, it is required that the Submitter add a refining 'element' to create unique Product Names that align to unique Product ID Numbers.  This refining element can be numeric, alpha or alpha-numeric.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"C"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PR007",
    "DataElementName":"Other Product Benefit Description",
    "CHIA_Notes":"",
    "NetezzaColumnName":"OTHERPRODUCTBENEFITDESCRIPTIONCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":80,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Benefit Description",
    "ElementSubmissionGuideline":"Report the Other Product description when the product's Product Benefit does not fall within the standard listing for PR006 Product Benefit Type  EXAMPLE:  Chiropractic Services",
    "Condition":"Required when PR006 = 0 <zero>",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PR015",
    "DataElementName":"Other Product Line of Business Model",
    "CHIA_Notes":"",
    "NetezzaColumnName":"OTHERPRODUCTLINEOFBUSINESSMODELCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":30,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Defines Product Line of Business when Other is selected",
    "ElementSubmissionGuideline":"Report the Other Product Line of Business Model here when PR004 reports ZZ. ",
    "Condition":"Required when PR004 = ZZ",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PR016",
    "DataElementName":"Other Risk Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"OTHERRISKTYPECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":30,
    "FLAG_Carrier_Specific_TLKP":"",
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Defines Risk Type Other is selected",
    "ElementSubmissionGuideline":"Report the Other Risk Type here when PR008 reports 0 <zero>.",
    "Condition":"Required when PR008 = 0 <zero>",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  }
];