// Spiro Ganas
// 11/13/15
//
// Creates a variable that stores the PV data dictionary in the JSON format.
// This is used to feed data to the AngularJS website.

var PV_JSON = [
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV1",
    "DataElementName":"County of Provider",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_COUNTY",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":24,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV2",
    "DataElementName":"County of Provider Mailing Address",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_MAILINGCOUNTY",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":24,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV3",
    "DataElementName":"Release ID",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"RELEASEID",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":7,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV5",
    "DataElementName":"Medicaid/HSN Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICAIDHSNINDICATOR",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":5,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV6",
    "DataElementName":"Provider Census Tract",
    "CHIA_Notes":"Melissa Data source",
    "NetezzaColumnName":"STANDARDIZED_CENSUSTRACT",
    "Other_NOTE":"Melissa Data source",
    "DataType":"varchar",
    "DataLength":6,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV7",
    "DataElementName":"Provider Census Block",
    "CHIA_Notes":"Melissa Data source",
    "NetezzaColumnName":"STANDARDIZED_CENSUSBLOCK",
    "Other_NOTE":"Melissa Data source",
    "DataType":"varchar",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV8",
    "DataElementName":"Mailing Census Tract",
    "CHIA_Notes":"Melissa Data source",
    "NetezzaColumnName":"STANDARDIZED_MAILINGCENSUSTRACT",
    "Other_NOTE":"Melissa Data source",
    "DataType":"varchar",
    "DataLength":6,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV9",
    "DataElementName":"Mailing Census Block",
    "CHIA_Notes":"Melissa Data source",
    "NetezzaColumnName":"STANDARDIZED_MAILINGCENSUSBLOCK",
    "Other_NOTE":"Melissa Data source",
    "DataType":"varchar",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"Derived-PV10",
    "DataElementName":"Provider Delegate",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LINKINGPROVIDERDELEGATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"",
    "ElementSubmissionGuideline":"",
    "Condition":"NA",
    "ThresholdPercent":"NA",
    "Category":"NA"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV001",
    "DataElementName":"Payer",
    "CHIA_Notes":"Required by IT for internal linkage",
    "NetezzaColumnName":"ORGID",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":6,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"CHIA defined and maintained unique identifier",
    "ElementSubmissionGuideline":"Report the Unique Submitter ID as defined by CHIA here.  This must match the Submitter ID reported in HD002.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV002",
    "DataElementName":"Plan Provider ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LINKINGPLANPROVIDERID",
    "Other_NOTE":"",
    "DataType":"BigInt",
    "DataLength":null,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Carrier Unique Provider Code",
    "ElementSubmissionGuideline":"Report the submitter assigned unique number for every service provider (persons, facilities or other entities involved in claims transactions) that it has in its system(s).  This element may or may not contain the provider NPI, but should not contain an individual�s SSN.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV006",
    "DataElementName":"License Id",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LICENSEIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":25,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"State practice license ID",
    "ElementSubmissionGuideline":"Report the state license number for the provider identified in PV002. For a doctor this is the medical license for a non-doctor this is the practice license.  Do not use zero-fill.  If not available, or not applicable, such as for a group or corporate entity, do not report any value here.  ",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV007",
    "DataElementName":"Medicaid Id",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICAIDIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":25,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"MassHealth-assigned Provider ID",
    "ElementSubmissionGuideline":"Report the Massachusetts State Medicaid number for the provider identified in PV002.  Do not use zero-fill.  Do not report any value if not available, or not applicable, such as for a group or corporate entity. ",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV008",
    "DataElementName":"Last Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"LASTNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":50,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Last name of the Provider in PV002",
    "ElementSubmissionGuideline":"Report the individual's last name here. Do not report any value here for facility or non-individual provider records.  Report non-person entities in PV012 Entity Name.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV009",
    "DataElementName":"First Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"FIRSTNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":50,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"First name of the Provider in PV002",
    "ElementSubmissionGuideline":"Report the individual's first name here. Do not report any value here for facility or non-individual provider records.  Report non-person entities in PV012 Facility Name.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV010",
    "DataElementName":"Middle Initial",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MIDDLEINITIALCLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Middle initial of the Provider in PV002",
    "ElementSubmissionGuideline":"Report the individual's middle initial here. Do not report any value here for facility or non-individual provider records.  Report non-person entities in PV012 Facility Name.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.01",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV011",
    "DataElementName":"Suffix",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SUFFIX",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Suffix of the Provider in PV002",
    "ElementSubmissionGuideline":"Report the individual's name suffix here. Do not report any value here for facility or non-individual provider records.  Report non-person entities in PV012 Facility Name.  EXAMPLE:  0 = Unknown / Not Applicable",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.01",
    "Category":"Z"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV012",
    "DataElementName":"Entity Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ENTITYNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":100,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Group / Facility name",
    "ElementSubmissionGuideline":"Report the Provider Entity Name when  Provider ID does not equal 1 (person). . This should only be populated for facilities or groups. Limited punctuation may be included.",
    "Condition":"Required when PV034 = 2, 3, 4, 5, 6, 7, or 0",
    "ThresholdPercent":"0.98",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV013",
    "DataElementName":"Entity Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ENTITYCODECLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider entity code",
    "ElementSubmissionGuideline":"Report the value that defines the entity provider type.  EXAMPLE:  12 = Acute Hospital",
    "Condition":"Required when PV034 does not = 1",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV014",
    "DataElementName":"Gender Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"GENDERCODECLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Gender of Provider identified in PV002",
    "ElementSubmissionGuideline":"Report provider gender in alpha format as found on certification, contract and / or license.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV015",
    "DataElementName":"Provider DOB (Year Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DOBDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider's date of birth",
    "ElementSubmissionGuideline":"Report the individual's date of birth in CCYYMMDD Format.  Only applies to providers identified as Entity = Person.  Do not report any value here for non-person entities, e.g. Professional Groups, Medical Sites.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV015",
    "DataElementName":"Provider DOB (Month Only)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DOBDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider's date of birth",
    "ElementSubmissionGuideline":"Report the individual's date of birth in CCYYMMDD Format.  Only applies to providers identified as Entity = Person.  Do not report any value here for non-person entities, e.g. Professional Groups, Medical Sites.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV016",
    "DataElementName":"Street Address1 Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_STREETADDRESS1NAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":50,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Street address of the Provider",
    "ElementSubmissionGuideline":"Report the physical street address where provider sees plan members.  If only mailing address is available, please send the mailing address in this element  in addition to putting it in the mailing address element .  If the provider sees members at two locations the provider should have a unique record for each to capture each site where the provider practices.  ",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV017",
    "DataElementName":"Street Address2 Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_STREETADDRESS2NAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":50,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Street Address 2 of the Provider",
    "ElementSubmissionGuideline":"Report the physical street address where provider sees plan members.  If only mailing address is available, please send the mailing address in this element in addition to putting it in the mailing address element.  If the provider sees members at two locations the provider should have a unique record for each to capture each site where the provider practices.  ",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV018",
    "DataElementName":"City Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_CITYNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":35,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"City of the Provider",
    "ElementSubmissionGuideline":"Report the city name where provider sees plan members.  If only mailing address is available, please send the mailing address in this element in addition to putting it in the mailing address element.  If the provider sees members at two locations the provider should have a unique record for each to capture each site where the provider practices. ",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV019",
    "DataElementName":"State Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_STATEORCODE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"State of the Provider",
    "ElementSubmissionGuideline":"Report the state of the site in which the provider sees plan members.  When only a mailing address is available, populate with mailing state here as well as PV026.  When a provider sees patients at two or more locations,  the provider should have a unique record for each location to capture all possible practice sites. ",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV020",
    "DataElementName":"Country Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"COUNTRYCODE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":3,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Country Code of the Provider",
    "ElementSubmissionGuideline":"Report the three-character country code as defined by ISO 3166-1, Alpha 3.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV021",
    "DataElementName":"ZIP Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_ZIPCODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":9,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Zip code of the Provider",
    "ElementSubmissionGuideline":"Report the 5 or 9 digit Zip Code as defined by the United States Postal Service.  When submitting the 9-digit Zip Code do not include hyphen.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV022",
    "DataElementName":"Taxonomy",
    "CHIA_Notes":"",
    "NetezzaColumnName":"TAXONOMYCLEANED",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":10,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Taxonomy Code",
    "ElementSubmissionGuideline":"Report the standard code that defines this provider for this line of service.  Taxonomy values allow for the reporting of many types of clinicians, assistants and technicians, where applicable, as well as Physicians, Nurses, Groups, Facilities, etc.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0.75",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV023",
    "DataElementName":"Mailing Street Address1 Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_MAILINGSTREETADDRESS1NAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":50,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Street address of the Provider / Entity",
    "ElementSubmissionGuideline":"Report the mailing address of the Provider / Entity in PV002.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV024",
    "DataElementName":"Mailing Street Address2 Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_MAILINGSTREETADDRESS2NAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":50,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Secondary Street address of the Provider / Entity",
    "ElementSubmissionGuideline":"Report the mailing address of the Provider / Entity in PV002.",
    "Condition":"All",
    "ThresholdPercent":"0.02",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV025",
    "DataElementName":"Mailing City Name",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_MAILINGCITYNAMECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":35,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"City name of the Provider / Entity",
    "ElementSubmissionGuideline":"Report the mailing city address of the Provider / Entity in PV002.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV026",
    "DataElementName":"Mailing State Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_MAILINGSTATECODE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"State name of the Provider / Entity",
    "ElementSubmissionGuideline":"Report the mailing state address of the Provider / Entity in PV002.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV027",
    "DataElementName":"Mailing Country Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MAILINGCOUNTRYCODE",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":3,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Country name of the Provider / Entity",
    "ElementSubmissionGuideline":"Report the three-character country code as defined by ISO 3166-1, Alpha 3.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV028",
    "DataElementName":"Mailing Zip Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_MAILINGZIPCODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":9,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Zip code of the Provider",
    "ElementSubmissionGuideline":"Report the 5 or 9 digit Zip Code as defined by the United States Postal Service.  When submitting the 9-digit Zip Code do not include hyphen.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV029",
    "DataElementName":"Provider Type Code",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERTYPECODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":10,
    "FLAG_Carrier_Specific_TLKP":1,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Provider Type Code",
    "ElementSubmissionGuideline":"Report the Provider Type code associated with the individual provider or facility.  The carrier/submitter must provide the MA APCD with Reference tables. This element distinguishes clinicians, facilities, and other.  Clinicians are physicians and other practitioners who can perform an E&M service (thereby start an episode of care).  Facilities can sometimes start episodes (i.e. patient goes to ER at onset of symptoms).  Providers classified as 'other' never start episodes. The MA APCD may use this element to perform further clinical and analytic grouping.  Entities not seeing patients should have a classification of 'Other'.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A1"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV030",
    "DataElementName":"Primary Specialty Code (Standard/Carrier-Specific Custom Values)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRIMARYSPECIALTYCODE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":3,
    "FLAG_Carrier_Specific_TLKP":1,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Specialty Code",
    "ElementSubmissionGuideline":"Report the standard Primary Specialty code of the Provider here.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV031",
    "DataElementName":"Provider Organization ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERORGANIZATIONID",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":6,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"CHIA defined and maintained Org ID for Providers",
    "ElementSubmissionGuideline":"Report the Local Practice Group OrgID number as assigned / maintained by CHIA for Total Medical Expense (TME) reporting  Data must be reported in aggregate for all practices in which the Local Practice Group�s member months are below 36,000 and the practice has no parent Physicians� Group.� This group is to be identified as �Groups below minimum threshold� with an ORGID of 999996.",
    "Condition":"Required when submitter is identified as a TME/RP Submitter ",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV032",
    "DataElementName":"Registered Provider Organization ID (RPO)",
    "CHIA_Notes":"No data",
    "NetezzaColumnName":"REGISTEREDPROVIDERORGANIZATIONIDCLEANED",
    "Other_NOTE":"",
    "DataType":"Char",
    "DataLength":30,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Registered Provider Organization ID",
    "ElementSubmissionGuideline":"Report the Health Policy Commission-assigned unique identifier for every service provider (persons, facilities or other entities involved in claims transactions) that it has in its system(s).� This information is required for TME/RP reporting and analysis.",
    "Condition":"Assigned submitters only",
    "ThresholdPercent":"0",
    "Category":"Z"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV034",
    "DataElementName":"ProviderIDCode",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERIDCODECLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider Identification Code",
    "ElementSubmissionGuideline":"Report the value that defines type of entity associated with PV002.  The value reported here drives intake edits for quality purposes.  EXAMPLE:  1 = Person; Physician, Clinician, Orthodontist, etc.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV036",
    "DataElementName":"Medicare Id",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICAREIDCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":30,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Provider's Medicare Number, other than UPIN",
    "ElementSubmissionGuideline":"Report the Medicare ID (OSCAR, Certification, Other, Unspecified, NSC or PIN) of the provider or entity in PV002.  Do not report UPIN here, see PV004.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0.9",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV037",
    "DataElementName":"Begin Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"BEGINDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":8,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider Start Date",
    "ElementSubmissionGuideline":"Report the date the provider or facility becomes eligible / contracted to perform services for plan members in CCYYMMDD Format.  Do not report any value here for providers that do not render services.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV037",
    "DataElementName":"Begin Date - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"BEGINDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider Start Date",
    "ElementSubmissionGuideline":"Report the date the provider or facility becomes eligible / contracted to perform services for plan members in CCYYMMDD Format.  Do not report any value here for providers that do not render services.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV037",
    "DataElementName":"Begin Date - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"BEGINDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider Start Date",
    "ElementSubmissionGuideline":"Report the date the provider or facility becomes eligible / contracted to perform services for plan members in CCYYMMDD Format.  Do not report any value here for providers that do not render services.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV038",
    "DataElementName":"End Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ENDDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":8,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider End Date",
    "ElementSubmissionGuideline":"Report the Date the provider or facility is no longer eligible to perform services for plan members / insureds in CCYYMMDD Format. Do not report any value here for providers that are still actively eligible to provide services, or Providers who do not render services (i.e., Parent Organizations).",
    "Condition":" All ",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV038",
    "DataElementName":"End Date - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ENDDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider End Date",
    "ElementSubmissionGuideline":"Report the Date the provider or facility is no longer eligible to perform services for plan members / insureds in CCYYMMDD Format. Do not report any value here for providers that are still actively eligible to provide services, or Providers who do not render services (i.e., Parent Organizations).",
    "Condition":" All ",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV038",
    "DataElementName":"End Date - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ENDDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider End Date",
    "ElementSubmissionGuideline":"Report the Date the provider or facility is no longer eligible to perform services for plan members / insureds in CCYYMMDD Format. Do not report any value here for providers that are still actively eligible to provide services, or Providers who do not render services (i.e., Parent Organizations).",
    "Condition":" All ",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV039",
    "DataElementName":"National Provider ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"NATIONALPROVIDERIDCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":10,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"National Provider Identification (NPI) of the Provider",
    "ElementSubmissionGuideline":"Report the NPI of the Provider / Clinician / Facility / Organization defined in this record.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0.98",
    "Category":"A"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV040",
    "DataElementName":"National Provider2 ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"NATIONALPROVIDER2IDCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":10,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"National Provider Identification (NPI) of the Provider",
    "ElementSubmissionGuideline":"Report the Secondary or Other NPI of the Provider / Clinician / Facility / Organization defined in this record.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0.01",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV042",
    "DataElementName":"Secondary Specialty2 Code (Standard/Carrier-Specific Custom Values)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SECONDARYSPECIALTY2CODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":10,
    "FLAG_Carrier_Specific_TLKP":1,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Specialty Code",
    "ElementSubmissionGuideline":"Report the submitter's proprietary specialty code for the provider here.  Known additional specialty code for a provider should be populated in elements PV043 and PV044.  Value comes from a Carrier Defined Table only.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5 and PV030 is blank",
    "ThresholdPercent":"0.9",
    "Category":"A"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV043",
    "DataElementName":"Secondary Specialty3 Code (Standard/Carrier-Specific Custom Values)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SECONDARYSPECIALTY3CODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":10,
    "FLAG_Carrier_Specific_TLKP":1,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Specialty Code",
    "ElementSubmissionGuideline":"See mapping notes for primary specialty code in PV030.  Known additional specialty code for a provider should be populated in this element.  Value can come from either a Carrier Defined Table or the External Code Source.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV044",
    "DataElementName":"Secondary Specialty4 Code (Standard/Carrier-Specific Custom Values)",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SECONDARYSPECIALTY4CODECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":10,
    "FLAG_Carrier_Specific_TLKP":1,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Specialty Code",
    "ElementSubmissionGuideline":"See mapping notes for primary specialty code in PV030.  Known additional specialty code for a provider should be populated in this element.  Value can come from either a Carrier Defined Table or the External Code Source.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV045",
    "DataElementName":"P4PFlag",
    "CHIA_Notes":"",
    "NetezzaColumnName":"P4PFLAG",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Provider Contract Payment",
    "ElementSubmissionGuideline":"Report the value that defines the element.  Pay-for-performance bonuses or year-end withhold returns based on performance for at least one service performed by this provider within the month.       EXAMPLE: 1 = Yes, provider has a contract incentive.",
    "Condition":"Required when PV034 = 1,  2, or 3",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV046",
    "DataElementName":"NonClaimsFlag",
    "CHIA_Notes":"",
    "NetezzaColumnName":"NONCLAIMSFLAG",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Provider Contract Payment",
    "ElementSubmissionGuideline":"Report the value that defines the element.  NonClaims payments that occur at least once within the month must be reported.   EXAMPLE: 1 = Yes, provider may be eligible to receive other payments not flowing through the claims system.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV047",
    "DataElementName":"Uses Electronic Medical Records",
    "CHIA_Notes":"",
    "NetezzaColumnName":"USESELECTRONICMEDICALRECORDS",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Filler",
    "ElementSubmissionGuideline":"the MA APCD reserves this field. Do not populate with any data. ",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"Z"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV048",
    "DataElementName":"EMR Vendor",
    "CHIA_Notes":"",
    "NetezzaColumnName":"EMRVENDORCLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":40,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Filler",
    "ElementSubmissionGuideline":"The MA APCD reserves the field. Do not populate with any data.",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"Z"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV049",
    "DataElementName":"Accepting New Patients",
    "CHIA_Notes":"",
    "NetezzaColumnName":"ACCEPTINGNEWPATIENTSCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - New Patients Accepted",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, provider or provider group is accepting new patients as of the day the file was created for this submission. ",
    "Condition":"Required when PV034 = 1, 2, or 3",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV050",
    "DataElementName":"Offers e-Visits",
    "CHIA_Notes":"",
    "NetezzaColumnName":"OFFERSEVISITS",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - eVisit Option",
    "ElementSubmissionGuideline":"The MA APCD reserves this field.  Do not populate with any data.",
    "Condition":"All",
    "ThresholdPercent":"0",
    "Category":"Z"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV052",
    "DataElementName":"Has multiple offices",
    "CHIA_Notes":"",
    "NetezzaColumnName":"HASMULTIPLEOFFICESCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Multiple Office Provider",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, provider has multiple offices.  ",
    "Condition":"Required when PV034 = 1, 2, or 3",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV054",
    "DataElementName":"Medical/Healthcare Home ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"MEDICALHEALTHCAREHOMEID_LINKAGE_ID",
    "Other_NOTE":"",
    "DataType":"BigInt",
    "DataLength":15,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Medical Home Identification Number",
    "ElementSubmissionGuideline":"Report the identifier of the patient-centered medical home the provider is linked-to here. The value in this element must have a corresponding Provider ID (PV002) in this or a previously submitted provider file.",
    "Condition":"Require when PV034  = 1, 2, or 3",
    "ThresholdPercent":"0",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV055",
    "DataElementName":"PCP Flag",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PCPFLAGCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Provider is a PCP",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, provider is a PCP.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV056",
    "DataElementName":"Provider Affiliation",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERAFFILIATION_LINKAGE_ID",
    "Other_NOTE":"",
    "DataType":"BigInt",
    "DataLength":30,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"Y",
    "Redaction":"",
    "Description":"Provider Affiliation Code",
    "ElementSubmissionGuideline":"Report the Provider ID for any affiliation the provider has with another entity or parent company.  If the provider is associated only with self, record the same value here as PV002.",
    "Condition":"All",
    "ThresholdPercent":"0.99",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV057",
    "DataElementName":"Provider Telephone",
    "CHIA_Notes":"",
    "NetezzaColumnName":"STANDARDIZED_TELEPHONEPROVIDERTELEPHONECLEANED",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":10,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"Y",
    "Description":"Telephone number associated with the provider identified in PV002",
    "ElementSubmissionGuideline":"Report the telephone number of the provider associated with the identification in PV002.  Do not separate components with hyphens, spaces or other special characters.",
    "Condition":"All",
    "ThresholdPercent":"0.1",
    "Category":"C"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV058",
    "DataElementName":"Delegated Provider Record Flag",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DELEGATEDPROVIDERRECORDFLAGCLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Delegated Record",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, provider record was sourced from the delegated provider�s system.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV060",
    "DataElementName":"Office Type",
    "CHIA_Notes":"",
    "NetezzaColumnName":"OFFICETYPECLEANED",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Cleaned",
    "Hashed":"",
    "Redaction":"",
    "Description":"Office Type Code",
    "ElementSubmissionGuideline":"Report the value that defines the provider's service setting.  EXAMPLE:  1 = Facility",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV061",
    "DataElementName":"Prescribing Provider",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PRESCRIBINGPROVIDER",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Prescribing Authority",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, provider has prescribing privileges for pharmaceuticals or DME.",
    "Condition":"All",
    "ThresholdPercent":"1",
    "Category":"A2"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV062",
    "DataElementName":"Provider Affiliation Start Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERAFFILIATIONSTARTDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":8,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider Start Date",
    "ElementSubmissionGuideline":"Report the start date of provider's relationship with parent entity / group in PV056 (Provider Affiliation) in CCYYMMDD Format.  Providers that are self-affiliated (or no affiliation) should have the same value reported here as in PV037.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV062",
    "DataElementName":"Provider Affiliation Start Date - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERAFFILIATIONSTARTDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider Start Date",
    "ElementSubmissionGuideline":"Report the start date of provider's relationship with parent entity / group in PV056 (Provider Affiliation) in CCYYMMDD Format.  Providers that are self-affiliated (or no affiliation) should have the same value reported here as in PV037.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV062",
    "DataElementName":"Provider Affiliation Start Date - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERAFFILIATIONSTARTDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider Start Date",
    "ElementSubmissionGuideline":"Report the start date of provider's relationship with parent entity / group in PV056 (Provider Affiliation) in CCYYMMDD Format.  Providers that are self-affiliated (or no affiliation) should have the same value reported here as in PV037.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"A0"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV063",
    "DataElementName":"Provider Affiliation End Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERAFFILIATIONENDDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":8,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider End Date",
    "ElementSubmissionGuideline":"Report the end date of provider's relationship with parent entity / group in PV056 (Provider Affiliation) in CCYYMMDD Format.  Do not report any value here if the affiliation is still active, or if there is no known affiliation in PV056.  Self-affiliations should report the same value here as in PV038.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV063",
    "DataElementName":"Provider Affiliation End Date - Year",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERAFFILIATIONENDDATEYEAR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":4,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider End Date",
    "ElementSubmissionGuideline":"Report the end date of provider's relationship with parent entity / group in PV056 (Provider Affiliation) in CCYYMMDD Format.  Do not report any value here if the affiliation is still active, or if there is no known affiliation in PV056.  Self-affiliations should report the same value here as in PV038.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV063",
    "DataElementName":"Provider Affiliation End Date - Month",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PROVIDERAFFILIATIONENDDATEMONTH",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":2,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Derived",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider End Date",
    "ElementSubmissionGuideline":"Report the end date of provider's relationship with parent entity / group in PV056 (Provider Affiliation) in CCYYMMDD Format.  Do not report any value here if the affiliation is still active, or if there is no known affiliation in PV056.  Self-affiliations should report the same value here as in PV038.",
    "Condition":"All",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":2,
    "DataElementSource":"PV064",
    "DataElementName":"PPO Indicator",
    "CHIA_Notes":"",
    "NetezzaColumnName":"PPOINDICATOR",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":1,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Indicator - Provider PPO Contract",
    "ElementSubmissionGuideline":"Report the value that defines the element.  EXAMPLE: 1 = Yes, provider is a contracted network provider. ",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"1",
    "Category":"A0"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PV003",
    "DataElementName":"Tax Id",
    "CHIA_Notes":"",
    "NetezzaColumnName":"TAXID",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":9,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Federal Tax ID of non-individual Provider",
    "ElementSubmissionGuideline":"Report the Federal Tax ID of the Provider here. Do not use hyphen or alpha prefix.",
    "Condition":"Required when PV034 = 2, 3, 4, 5, 6, 7, or 0",
    "ThresholdPercent":"0.98",
    "Category":"A2"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PV004",
    "DataElementName":"UPIN Id - GIC Only",
    "CHIA_Notes":"",
    "NetezzaColumnName":"UPINID",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":6,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Unique Physician ID",
    "ElementSubmissionGuideline":"Report the UPIN for the Provider identified in PV002.  To report other Medicare Identifiers use PV036.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PV005",
    "DataElementName":"DEA ID",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DEAID",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":9,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider DEA",
    "ElementSubmissionGuideline":"Report the valid DEA ID of the individual, group or facility defined by PV002.  If not available or applicable, do not report any value here.",
    "Condition":"Required when PV034 = 0, 1, 2, 3, 4, or 5",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PV015",
    "DataElementName":"Provider DOB Date",
    "CHIA_Notes":"",
    "NetezzaColumnName":"DOBDATE",
    "Other_NOTE":"",
    "DataType":"int",
    "DataLength":8,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider's date of birth",
    "ElementSubmissionGuideline":"Report the individual's date of birth in CCYYMMDD Format.  Only applies to providers identified as Entity = Person.  Do not report any value here for non-person entities, e.g. Professional Groups, Medical Sites.",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.98",
    "Category":"B"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PV035",
    "DataElementName":"SSN Id",
    "CHIA_Notes":"",
    "NetezzaColumnName":"SSNID",
    "Other_NOTE":"",
    "DataType":"char",
    "DataLength":9,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"Encrypted",
    "Hashed":"",
    "Redaction":"",
    "Description":"Provider's Social Security Number",
    "ElementSubmissionGuideline":"Report the SSN of the individual provider in PV002. Do not zero-fill.  Do not report any value here if not available or not applicable. ",
    "Condition":"Required when PV034 = 1",
    "ThresholdPercent":"0.98",
    "Category":"A1"
  },
  {
    "ReleaseLevel":3,
    "DataElementSource":"PV041",
    "DataElementName":"GIC Provider Link ID",
    "CHIA_Notes":"No data available",
    "NetezzaColumnName":"",
    "Other_NOTE":"",
    "DataType":"varchar",
    "DataLength":25,
    "FLAG_Carrier_Specific_TLKP":null,
    "FieldType":"",
    "Hashed":"",
    "Redaction":"",
    "Description":"GIC Provider Link ID for GIC Carriers only",
    "ElementSubmissionGuideline":"Report the GIC Assigned Provider Link ID.  If not applicable, do not report any value here.",
    "Condition":"Required when Submitter is identified as a GIC Submitter",
    "ThresholdPercent":"0",
    "Category":"B"
  }
];